---
title: "Figure 4 TNAMSE"
author: "Axel Schmidt"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE, message=TRUE}
library(tidyverse)

args=c("results/parse_table/diagnostic_vars.tsv", 
       "results/parse_table/all_monogenic_vars.tsv", 
       "../../" )
args = commandArgs(trailingOnly=TRUE)
depth<-args[3]
path_solvedCases<-paste0(depth, args[1])
path_variants<-paste0(depth, args[2])

Case_Var<-read_tsv(file=path_solvedCases, guess_max = 2000, locale=locale(decimal_mark = ","))
vars<-read_tsv(file=path_variants)
```


```{r count_vars}
n_occur <- data.frame(table(Case_Var$case_ID_paper))
n_occur[n_occur$Freq > 1,]

Case_Var<-Case_Var%>%
  mutate(patientID_gene=paste0(case_ID_paper, ":", gene))

vars<-vars %>% 
  filter(abs(ACMG_class) >3 )%>%
  filter(case_ID_paper %in% Case_Var$case_ID_paper)%>%
  filter(variant_solves_case=="primary")

TN_vars_count<-vars %>% 
  group_by(gene)%>%
  summarise(number_of_variants=n()) %>%
  rename(GeneSymbol=gene)

write_tsv(TN_vars_count, file = "TN_vars_count.tsv")

```
