---
title: "Supporting populations"
author: "Axel Schmidt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

args=c("results/parse_table/all_cases.tsv",  
       "../../" )

args = commandArgs(trailingOnly=TRUE)
depth<-args[2]
in_file<-paste0(depth, args[1]) #

set.seed(1)

all_cases<-read_tsv(in_file, guess_max = 2000, locale=locale(decimal_mark = ",")) %>%
  distinct(case_ID_paper,.keep_all = TRUE) # remove double occuring cases (for security, should already be removed)

```

## pie chart

```{r plot_pops}

table(all_cases$population, useNA = "always")
table(all_cases$population, useNA = "always")/length(all_cases$population)

pops<-all_cases %>% 
  filter(!is.na(population))

table(pops$population, useNA = "always")
table(pops$population, useNA = "always")/length(pops$population)


sum(!is.na(pops$population))

pieplot<-ggplot(data=pops) +
  geom_bar(stat = "count", aes(x=factor(1), fill=population))+
  scale_y_continuous()+
  coord_polar("y")+
  theme_void()+
  scale_fill_brewer(palette = "Set1")
print(pieplot)
ggsave(pieplot, filename="pieplot_population.pdf",width=4, height=4)  
ggsave(pieplot, filename="pieplot_population.png",width=4, height=4, dpi=600)  

```

```{r plot_sex}

table(all_cases$sex, useNA = "always")
table(all_cases$sex, useNA = "always")/length(all_cases$population)



sum(!is.na(pops$population))

pieplot<-ggplot(data=all_cases) +
  geom_bar(stat = "count", aes(x=factor(1), fill=sex))+
  scale_y_continuous()+
  coord_polar("y")+
  theme_void()+
  scale_fill_brewer(palette = "Set1")
print(pieplot)
ggsave(pieplot, filename="pieplot_sex.pdf",width=4, height=4)  
ggsave(pieplot, filename="pieplot_sex.png",width=4, height=4, dpi=600)  



```

